# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Running Pytest testcases

on:
  push:
    branches: [ "without_fastapi" ]
  pull_request:
    branches: [ "without_fastapi" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Read Python version
      id: pyver
      run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
        sudo apt-get install -y ffmpeg
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest